name: Format Validate

on:
  push:
    branches: ["main"]

jobs:
  Terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Terraform Init
        run: terraform init -backend=false -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Format
        run: terraform fmt -check -recursive -diff -no-color
