name: Terraform

on:
  push:
    branches: ["main"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Terraform Init
        run: terraform init -backend=true -backend-config="config/dev/backend.hcl"

      - name: Terraform Plan
        run: terraform plan -no-color -compact-warnings -out=tfplan

      - name: Terraform Apply
        run: terraform apply -no-color -compact-warnings -input=false tfplan

      - name: Terraform Plan
        run: terraform plan -no-color -compact-warnings -destroy -out=destroyplan

      - name: Terraform Destroy
        run: terraform apply -no-color -compact-warnings -input=false -destroy tfplan
